theme {
    color_scheme = /home/quiet/.local/share/color-schemes/DankMatugen.colors
    icon_theme = breeze-dark
    style = kvantum
    font_fixed = DejaVu LGC Sans
    font_fixed_size = 12
    font = DejaVu LGC Sans
    font_size = 12
}

misc {
    single_click_activate = 1
    menus_have_icons = 1
    shortcuts_for_context_menus = 1
}
